function Q = XiMatrix(q)
%XIMATRIX Summary of this function goes here
%   Detailed explanation goes here
    Q = [ -q(2) -q(3) -q(4);...
           q(1) -q(4)  q(3);...
           q(4)  q(1) -q(2);...
          -q(3)  q(2)  q(1)];
end

